function rowsFromCSV(text){let out=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))out.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))out.push(row);return out}
const number=v=>Number(String(v||'').replace(/[$,\s]/g,''))||0;
const dateKey=v=>{const m=String(v||'').match(/(\d{4})[.\-](\d{2})[.\-](\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:''};
function addHistory(data,source,accountId,file,added){data.importHistory=data.importHistory||[];data.importHistory.unshift({id:crypto.randomUUID(),source,accountId,file,added,at:new Date().toISOString()})}
function fundedNext(data,text,accountId,file){const rows=rowsFromCSV(text.replace(/^\uFEFF/,''));if(rows.length<2)throw new Error('CSV فارغ');const h=rows.shift().map(x=>x.trim()), ix=k=>h.indexOf(k);const required=['Ticket ID','Open Time','Open Price','Close Time','Close Price','Profit','Lots','Commission','Swap','Symbol','Type'];if(required.some(x=>ix(x)<0))throw new Error('هذا ليس FundedNext CSV بالتنسيق المتوقع');let added=0;for(const r of rows){const ticket=r[ix('Ticket ID')];if(!ticket)continue;const open=String(r[ix('Close Time')]||'').toLowerCase().includes('currently running'),profit=number(r[ix('Profit')]),commission=number(r[ix('Commission')]),swap=number(r[ix('Swap')]);const base={accountId,source:'FundedNext CSV',ticket,openTime:r[ix('Open Time')],entry:number(r[ix('Open Price')]),profit,commission,swap,netProfit:profit+commission+swap,lots:number(r[ix('Lots')]),symbol:r[ix('Symbol')],side:r[ix('Type')],sl:number(r[ix('SL')]),tp:number(r[ix('TP')]),pips:number(r[ix('Pips')]),volume:number(r[ix('Volume')])};if(open){data.openPositions=data.openPositions||[];const pos={...base,id:'fundednext-open:'+ticket,importId:'fundednext-open:'+ticket};const i=data.openPositions.findIndex(x=>x.importId===pos.importId);if(i>=0)data.openPositions[i]=pos;else data.openPositions.push(pos);continue}if(data.trades.some(t=>t.importId==='fundednext:'+ticket))continue;data.openPositions=(data.openPositions||[]).filter(x=>x.ticket!==ticket);data.trades.unshift({...base,id:crypto.randomUUID(),importId:'fundednext:'+ticket,closeTime:r[ix('Close Time')],date:dateKey(r[ix('Close Time')]||r[ix('Open Time')]),close:number(r[ix('Close Price')]),resultR:null,note:'Imported from FundedNext CSV',tags:'FundedNext'});added++}const a=data.accounts.find(x=>x.id===accountId);if(a)a.lastFundedNextImport=new Date().toISOString();addHistory(data,'FundedNext CSV',accountId,file,added);return {added,headers:h}}
function cleanHtml(v){return String(v||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()}
function rowsFromHTML(text){let rows=[];for(const tr of text.match(/<tr[\s\S]*?<\/tr>/gi)||[]){let row=[];for(const td of tr.match(/<(?:td|th)[^>]*>[\s\S]*?<\/(?:td|th)>/gi)||[])row.push(cleanHtml(td));if(row.length)rows.push(row)}return rows}
function field(headers,names){const h=headers.map(x=>x.toLowerCase().replace(/[^a-z]/g,''));for(const n of names){const i=h.indexOf(n.toLowerCase().replace(/[^a-z]/g,''));if(i>=0)return i}return -1}
function mt5(data,text,accountId,file,isHtml){const rows=isHtml?rowsFromHTML(text):rowsFromCSV(text);const at=rows.findIndex(r=>field(r,['Symbol'])>=0&&field(r,['Type'])>=0&&field(r,['Profit'])>=0);if(at<0)throw new Error('لم أجد جدول صفقات MT5 في التقرير');const h=rows[at],ix=n=>field(h,n),symbol=ix(['Symbol','Instrument']),type=ix(['Type','Side']),profit=ix(['Profit','P/L']),ticket=ix(['Ticket','Deal','Position']),openTime=ix(['Open Time','Time']),closeTime=ix(['Close Time','CloseTime']),openPrice=ix(['Open Price','Price Open']),closePrice=ix(['Close Price','Price Close']),lots=ix(['Volume','Lots']),commission=ix(['Commission']),swap=ix(['Swap']),sl=ix(['S/L','SL']),tp=ix(['T/P','TP']);if(symbol<0||type<0||profit<0)throw new Error('أعمدة MT5 الأساسية غير موجودة');let added=0;for(const r of rows.slice(at+1)){if(r.length<h.length*.55)continue;const sym=r[symbol],side=r[type];if(!sym||!side||!/buy|sell/i.test(side))continue;const id=(ticket>=0?r[ticket]:'')||`${sym}:${r[closeTime]||r[openTime]}:${r[profit]}`;if(data.trades.some(t=>t.importId==='mt5:'+id))continue;const pr=number(r[profit]),co=commission>=0?number(r[commission]):0,sw=swap>=0?number(r[swap]):0;data.trades.unshift({id:crypto.randomUUID(),importId:'mt5:'+id,accountId,source:'MT5 Report',ticket:id,openTime:openTime>=0?r[openTime]:'',closeTime:closeTime>=0?r[closeTime]:'',date:dateKey(closeTime>=0?r[closeTime]:r[openTime]),entry:openPrice>=0?number(r[openPrice]):0,close:closePrice>=0?number(r[closePrice]):0,profit:pr,commission:co,swap:sw,netProfit:pr+co+sw,lots:lots>=0?number(r[lots]):0,symbol:sym,side:/buy/i.test(side)?'Buy':'Sell',sl:sl>=0?number(r[sl]):0,tp:tp>=0?number(r[tp]):0,resultR:null,note:'Imported from MT5 Report',tags:'MT5'});added++}const a=data.accounts.find(x=>x.id===accountId);if(a)a.lastMT5Import=new Date().toISOString();addHistory(data,'MT5 Report',accountId,file,added);return {added,headers:h}}
module.exports={rowsFromCSV,fundedNext,mt5};
