let signals=[],selected=null, settings={}, taskKeys=['plan','news','signals','review'];
const $=x=>document.querySelector(x), day=()=>new Date().toISOString().slice(0,10), key=x=>'cisd.'+day()+'.'+x;
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3200)}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('show'));document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('show');document.querySelector(`nav [data-page="${id}"]`).classList.add('active')}
document.querySelectorAll('nav button').forEach(x=>x.onclick=()=>go(x.dataset.page));
function decisionOf(s){return localStorage.getItem('decision.'+s.SignalID)||'new'}function reasonOf(s){return localStorage.getItem('reason.'+s.SignalID)||''}
function taskDone(k){return localStorage.getItem(key(k))==='1'}function renderTasks(){let box=$('#tasks');box.innerHTML='';let labels={plan:['خطة الجلسة جاهزة','الأسواق والجلسة وحدودك محددة.'],news:['راجعت الأخبار المهمة','لا مفاجآت قريبة من وقت التنفيذ.'],signals:['صنّفت كل إشارات اليوم','راجع كل إشارة ظهرت في السجل.'],review:['مراجعة نهاية اليوم','اكتب ملاحظة قصيرة وصادقة.']};taskKeys.forEach(k=>{let d=document.createElement('div');d.className='task';d.innerHTML=`<input type="checkbox" ${taskDone(k)?'checked':''}><div><b>${labels[k][0]}</b><small>${labels[k][1]}</small></div>`;d.querySelector('input').onchange=e=>{localStorage.setItem(key(k),e.target.checked?'1':'0');render()};box.append(d)})}
function render(){let done=taskKeys.filter(taskDone).length,pending=signals.filter(x=>decisionOf(x)==='new').length,reviewed=signals.filter(x=>decisionOf(x)!=='new').length;let streak=Number(localStorage.getItem('cisd.streak')||0);if(done===4&&!localStorage.getItem(key('streak'))){streak++;localStorage.setItem('cisd.streak',streak);localStorage.setItem(key('streak'),'1')}let xp=done*10+reviewed*5+streak*5;$('#streak').textContent=streak+' 🔥';$('#xp').textContent=xp+' XP';$('#pending').textContent=pending;$('#completion').textContent=Math.round(done/4*100)+'%';$('#heroProgress').textContent=done+' من 4 مهام';$('#heroBar').style.width=(done/4*100)+'%';$('#heroText').textContent=done===4?'يوم منضبط مكتمل. أحسنت.':'خطوة واحدة صحيحة أفضل من عشر نوايا.';renderTasks();renderWeek();renderFeatured();renderSignals();$('#weeklySummary').innerHTML=`<b>${signals.length}</b> إشارة مستوردة اليوم<br><b>${reviewed}</b> قراراً مسجلاً<br><b>${pending}</b> إشارة تحتاج مراجعة<br>سلسلة الانضباط: <b>${streak}</b> أيام`;let n=localStorage.getItem(key('notes'))||'';if(document.activeElement!==$('#notes'))$('#notes').value=n}
function renderWeek(){let d=$('#weekDots');d.innerHTML='';['أ','إ','ث','أ','خ','ج','س'].forEach((x,i)=>{let a=document.createElement('i');a.className='week-dot '+(i===4?'today':i>4?'future':'');a.textContent=i<4?'✓':i===4?'◐':'—';a.title=x;d.append(a)})}
function filters(s){return [['Trend',s.Trend],['Fib',s.Fib],['MS',s.MS],['HTF',s.HTF],['Mom',s.MomVol]].filter(x=>x[1]==='1').map(x=>`<span class="filter">${x[0]}</span>`).join('')||'<span class="filter">لا فلاتر إضافية</span>'}
function renderFeatured(){let s=signals.find(x=>decisionOf(x)==='new'),box=$('#featured');if(!s){box.className='empty';box.textContent='لا توجد إشارات جديدة حالياً. الانتظار قرار أيضاً.';return}box.className='signal-card';box.innerHTML=`<div class="badge ${s.Direction.includes('+')?'buy':'sell'}">${s.Direction}</div><div><b>${s.Instrument} · ${s.TF}</b><small>${s.Session} · ${s.Grade} · Score ${s.Score}</small></div><span class="status new">قرارك؟</span>`;box.onclick=()=>{selected=s;go('signals');renderSignals()}}
function renderSignals(){let list=$('#signalList');list.innerHTML='';signals.forEach(s=>{let d=decisionOf(s), card=document.createElement('div');card.className='signal-card '+(selected?.SignalID===s.SignalID?'selected':'');card.innerHTML=`<div class="badge ${s.Direction.includes('+')?'buy':'sell'}">${s.Direction}</div><div><b>${s.Instrument} <span style="color:#8195ad;font-size:10px">· ${s.TF}</span></b><small>${s.SignalTimeNY} · ${s.Session} · ${s.Grade} · Score ${s.Score}</small></div><span class="status ${d}">${{new:'جديدة',placed:'وضعت أمراً',missed:'لم أدخل',rejected:'خارج خطتي'}[d]}</span>`;card.onclick=()=>{selected=s;renderSignals()};list.append(card)});let title=$('#chosenTitle'),meta=$('#chosenMeta'),f=$('#chosenFilters');if(selected){title.textContent=`${selected.Instrument} — ${selected.Direction}`;meta.textContent=`${selected.SignalTimeNY} · ${selected.TF} · ${selected.Session} · ${selected.Grade} · Score ${selected.Score}`;f.innerHTML=filters(selected)}else{title.textContent='اختر إشارة';meta.textContent='سيظهر هنا ملخص الإشارة وشروطها.';f.innerHTML=''}}
function decide(d){if(!selected){toast('اختر إشارة أولاً.');return}if(d==='missed'){let r=prompt('سبب عدم الدخول؟\nتردد / انتظار تأكيد زائد / خبر / خارج وقتي','تردد');if(r===null)return;localStorage.setItem('reason.'+selected.SignalID,r)}localStorage.setItem('decision.'+selected.SignalID,d);render();toast(d==='placed'?'تم تسجيل أنك وضعت أمراً.':d==='missed'?'تم تسجيل السبب. الصدق يبني تقدمك.':'تم تصنيف الإشارة خارج خطتك.')}
async function chooseCSV(){let p=await window.journal.selectCSV();if(p){settings.csvPath=p;labels();toast('تم اختيار ملف الإشارات.')}}async function chooseTerminal(k){let p=await window.journal.selectTerminal(k);if(p){settings[k]=p;labels();toast('تم حفظ اختصار المنصة محلياً.')}}async function launch(k){let r=await window.journal.launch(k);if(!r.ok){toast(r.reason==='not-configured'?'اختر اختصار MT5 أولاً من الإعدادات.':'تعذر فتح الاختصار: '+r.reason);go('settings')}else toast('تم فتح MT5. نفّذ قرارك بهدوء.')}
function labels(){$('#csvLabel').textContent=settings.csvPath||'لم يتم الاختيار';$('#fpLabel').textContent=settings.fundingPips||'لم يتم اختيار اختصار';$('#fnLabel').textContent=settings.fundedNext||'لم يتم اختيار اختصار'}function saveNotes(){localStorage.setItem(key('notes'),$('#notes').value);toast('تم حفظ ملاحظة اليوم ✓')}
(async()=>{settings=await window.journal.settings();labels();window.journal.onSignals(x=>{signals=x.sort((a,b)=>b.SignalTimeNY.localeCompare(a.SignalTimeNY));$('#connection').textContent='● متصل بإشارات JForex';render()});window.journal.onError(e=>{$('#connection').textContent='● خطأ: '+e});render()})();
