const assert=require('assert');
const fs=require('fs');const os=require('os');const path=require('path');
const {createStore}=require('../lib/store');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cisd-store-'));
const app={getPath:()=>dir};const store=createStore(app);
const legacy={version:0,accounts:[{id:'a',firm:'Test'}],trades:[],settings:{timezone:'GMT'}};
fs.writeFileSync(path.join(dir,'journal-data.json'),JSON.stringify(legacy));
let state=store.read();
assert.equal(state.settings.timezone,'GMT');
assert.equal(state.settings.newsProvider,'FREE');
assert.ok(Array.isArray(state.openPositions));
assert.ok(Array.isArray(state.backtestSignals));
assert.ok(Array.isArray(state.importHistory));
state.trades.push({id:'trade-1'});store.save(state);
state=store.read();assert.equal(state.trades.length,1);
fs.writeFileSync(path.join(dir,'journal-data.json'),'{bad json');
state=store.read();assert.ok(Array.isArray(state.accounts));
assert.ok(fs.readdirSync(dir).some(x=>x.includes('.corrupt-')));
fs.rmSync(dir,{recursive:true,force:true});
console.log('Store QA: PASS (migration, atomic save/read, corrupt recovery)');
